// ─── SalesSetu Demo Seed Data ──────────────────────────────────────────────
// 30+ Indian B2B companies with realistic data for demo mode

export const DEMO_COMPANIES = [
  {
    id: 'co_1', name: 'Zoho Corporation', website: 'zoho.com',
    industry: 'SaaS', city: 'Chennai', state: 'Tamil Nadu', country: 'India',
    employeeCount: 15000, revenue: '₹8,000 Cr', fundingStage: 'Bootstrapped',
    intentStatus: 'WARM', leadScore: 72, whyNowScore: 58,
    relationshipStatus: 'PROSPECT',
    description: 'Global SaaS company offering 50+ business applications.',
    recentDevelopments: 'Expanding into AI-powered analytics tools. Hiring heavily in BD.',
    technologies: ['React', 'Python', 'PostgreSQL'],
  },
  {
    id: 'co_2', name: 'Razorpay', website: 'razorpay.com',
    industry: 'FinTech', city: 'Bangalore', state: 'Karnataka', country: 'India',
    employeeCount: 3000, revenue: '₹1,200 Cr', fundingStage: 'Series F',
    intentStatus: 'HOT', leadScore: 91, whyNowScore: 87,
    relationshipStatus: 'CONTACTED',
    description: 'India\'s leading payment gateway and financial infrastructure provider.',
    recentDevelopments: 'Launched Razorpay Capital. Expanding to Southeast Asia. Hiring Head of Partnerships.',
    technologies: ['Node.js', 'Go', 'Kafka', 'AWS'],
  },
  {
    id: 'co_3', name: 'Freshworks', website: 'freshworks.com',
    industry: 'SaaS', city: 'Chennai', state: 'Tamil Nadu', country: 'India',
    employeeCount: 5000, revenue: '₹4,500 Cr', fundingStage: 'Public (NASDAQ)',
    intentStatus: 'HOT', leadScore: 88, whyNowScore: 82,
    relationshipStatus: 'ENGAGED',
    description: 'Customer engagement software for SMBs and enterprises.',
    recentDevelopments: 'Announced Freddy AI partnership program. Active RFP for sales automation.',
    technologies: ['Ruby on Rails', 'React', 'MySQL'],
  },
  {
    id: 'co_4', name: 'Meesho', website: 'meesho.com',
    industry: 'E-commerce', city: 'Bangalore', state: 'Karnataka', country: 'India',
    employeeCount: 4000, revenue: '₹5,700 Cr', fundingStage: 'Series F',
    intentStatus: 'WARM', leadScore: 65, whyNowScore: 60,
    relationshipStatus: 'PROSPECT',
    description: 'Social commerce platform connecting resellers with suppliers.',
    recentDevelopments: 'Launching new seller onboarding automation. Hiring enterprise sales team.',
    technologies: ['Python', 'Django', 'React', 'GCP'],
  },
  {
    id: 'co_5', name: 'PhonePe', website: 'phonepe.com',
    industry: 'FinTech', city: 'Bangalore', state: 'Karnataka', country: 'India',
    employeeCount: 4500, revenue: '₹2,900 Cr', fundingStage: 'Series E',
    intentStatus: 'HOT', leadScore: 85, whyNowScore: 79,
    relationshipStatus: 'PROSPECT',
    description: 'Digital payments platform with 450M+ registered users.',
    recentDevelopments: 'Entered insurance distribution. Partnership with international payment networks.',
    technologies: ['Java', 'Kafka', 'Cassandra', 'AWS'],
  },
  {
    id: 'co_6', name: 'BrowserStack', website: 'browserstack.com',
    industry: 'SaaS', city: 'Mumbai', state: 'Maharashtra', country: 'India',
    employeeCount: 1200, revenue: '₹800 Cr', fundingStage: 'Series A',
    intentStatus: 'HOT', leadScore: 94, whyNowScore: 91,
    relationshipStatus: 'MEETING_SCHEDULED',
    description: 'Cloud platform for web and mobile testing.',
    recentDevelopments: 'Active procurement for AI testing tools. RFP published last week.',
    technologies: ['Java', 'Selenium', 'AWS', 'React'],
  },
  {
    id: 'co_7', name: 'Postman', website: 'postman.com',
    industry: 'SaaS', city: 'Bangalore', state: 'Karnataka', country: 'India',
    employeeCount: 800, revenue: '₹600 Cr', fundingStage: 'Series D',
    intentStatus: 'WARM', leadScore: 77, whyNowScore: 68,
    relationshipStatus: 'CONTACTED',
    description: 'API platform used by 30M+ developers worldwide.',
    recentDevelopments: 'Expanding enterprise sales motion. Partnership program being revamped.',
    technologies: ['Electron', 'React', 'MongoDB', 'AWS'],
  },
  {
    id: 'co_8', name: 'upGrad', website: 'upgrad.com',
    industry: 'EdTech', city: 'Mumbai', state: 'Maharashtra', country: 'India',
    employeeCount: 5000, revenue: '₹2,100 Cr', fundingStage: 'Series H',
    intentStatus: 'WARM', leadScore: 69, whyNowScore: 55,
    relationshipStatus: 'PROSPECT',
    description: 'Online higher education platform with global presence.',
    recentDevelopments: 'Expanding B2B enterprise learning segment. Hiring corporate sales.',
    technologies: ['React', 'Python', 'AWS', 'PostgreSQL'],
  },
  {
    id: 'co_9', name: 'Darwinbox', website: 'darwinbox.com',
    industry: 'SaaS', city: 'Hyderabad', state: 'Telangana', country: 'India',
    employeeCount: 900, revenue: '₹400 Cr', fundingStage: 'Series D',
    intentStatus: 'HOT', leadScore: 89, whyNowScore: 85,
    relationshipStatus: 'CONTACTED',
    description: 'Cloud HR platform for enterprises in Asia.',
    recentDevelopments: 'Launching AI hiring module. Signed 3 new enterprise clients this quarter.',
    technologies: ['React', 'Node.js', 'AWS', 'PostgreSQL'],
  },
  {
    id: 'co_10', name: 'Chargebee', website: 'chargebee.com',
    industry: 'SaaS', city: 'Chennai', state: 'Tamil Nadu', country: 'India',
    employeeCount: 600, revenue: '₹350 Cr', fundingStage: 'Series H',
    intentStatus: 'WARM', leadScore: 74, whyNowScore: 66,
    relationshipStatus: 'PROSPECT',
    description: 'Subscription billing and revenue management platform.',
    recentDevelopments: 'Partnership with major accounting software vendors. Expanding India GTM.',
    technologies: ['Ruby', 'React', 'MySQL', 'AWS'],
  },
  {
    id: 'co_11', name: 'Lenskart', website: 'lenskart.com',
    industry: 'E-commerce', city: 'Faridabad', state: 'Haryana', country: 'India',
    employeeCount: 4000, revenue: '₹1,800 Cr', fundingStage: 'Series J',
    intentStatus: 'COLD', leadScore: 45, whyNowScore: 30,
    relationshipStatus: 'PROSPECT',
    description: 'Omnichannel eyewear retailer with 1000+ stores.',
    recentDevelopments: 'Expanding international operations. Opening stores in Middle East.',
    technologies: ['React', 'Node.js', 'MongoDB'],
  },
  {
    id: 'co_12', name: 'Clevertap', website: 'clevertap.com',
    industry: 'SaaS', city: 'Mumbai', state: 'Maharashtra', country: 'India',
    employeeCount: 700, revenue: '₹300 Cr', fundingStage: 'Series D',
    intentStatus: 'HOT', leadScore: 86, whyNowScore: 80,
    relationshipStatus: 'PROSPECT',
    description: 'Customer engagement and retention platform.',
    recentDevelopments: 'Seeking AI-powered sales automation partner. Active RFP open.',
    technologies: ['Scala', 'Kafka', 'Cassandra', 'React'],
  },
  {
    id: 'co_13', name: 'Leadsquared', website: 'leadsquared.com',
    industry: 'SaaS', city: 'Bangalore', state: 'Karnataka', country: 'India',
    employeeCount: 1200, revenue: '₹250 Cr', fundingStage: 'Series C',
    intentStatus: 'WARM', leadScore: 68, whyNowScore: 57,
    relationshipStatus: 'PROSPECT',
    description: 'CRM and marketing automation for high-velocity sales teams.',
    recentDevelopments: 'Expanding partnership ecosystem. Looking for integration partners.',
    technologies: ['React', '.NET', 'SQL Server', 'Azure'],
  },
  {
    id: 'co_14', name: 'Zetwerk', website: 'zetwerk.com',
    industry: 'Manufacturing', city: 'Bangalore', state: 'Karnataka', country: 'India',
    employeeCount: 2500, revenue: '₹12,000 Cr', fundingStage: 'Series F',
    intentStatus: 'WARM', leadScore: 61, whyNowScore: 49,
    relationshipStatus: 'PROSPECT',
    description: 'B2B manufacturing network platform.',
    recentDevelopments: 'Building digital supply chain tools. Hiring for technology partnerships.',
    technologies: ['React', 'Python', 'PostgreSQL', 'AWS'],
  },
  {
    id: 'co_15', name: 'HealthifyMe', website: 'healthifyme.com',
    industry: 'HealthTech', city: 'Bangalore', state: 'Karnataka', country: 'India',
    employeeCount: 1000, revenue: '₹450 Cr', fundingStage: 'Series D',
    intentStatus: 'COLD', leadScore: 42, whyNowScore: 28,
    relationshipStatus: 'PROSPECT',
    description: 'AI-powered nutrition and fitness platform.',
    recentDevelopments: 'Expanding B2B corporate wellness segment.',
    technologies: ['React Native', 'Python', 'TensorFlow', 'AWS'],
  },
  {
    id: 'co_16', name: 'Slice', website: 'sliceit.com',
    industry: 'FinTech', city: 'Bangalore', state: 'Karnataka', country: 'India',
    employeeCount: 800, revenue: '₹600 Cr', fundingStage: 'Series B',
    intentStatus: 'HOT', leadScore: 83, whyNowScore: 76,
    relationshipStatus: 'PROSPECT',
    description: 'Neo-banking and credit card platform for millennials.',
    recentDevelopments: 'Merging with North East Small Finance Bank. Major tech overhaul in progress.',
    technologies: ['Node.js', 'React', 'PostgreSQL', 'AWS'],
  },
  {
    id: 'co_17', name: 'Moengage', website: 'moengage.com',
    industry: 'SaaS', city: 'Bangalore', state: 'Karnataka', country: 'India',
    employeeCount: 900, revenue: '₹350 Cr', fundingStage: 'Series E',
    intentStatus: 'HOT', leadScore: 87, whyNowScore: 81,
    relationshipStatus: 'PROSPECT',
    description: 'Insights-led customer engagement platform for consumer brands.',
    recentDevelopments: 'Launched AI segment builder. Looking for sales automation integrations.',
    technologies: ['Python', 'Kafka', 'Spark', 'React'],
  },
  {
    id: 'co_18', name: 'Groww', website: 'groww.in',
    industry: 'FinTech', city: 'Bangalore', state: 'Karnataka', country: 'India',
    employeeCount: 3000, revenue: '₹1,500 Cr', fundingStage: 'Series E',
    intentStatus: 'WARM', leadScore: 67, whyNowScore: 52,
    relationshipStatus: 'PROSPECT',
    description: 'Investment platform for stocks, mutual funds, and crypto.',
    recentDevelopments: 'Expanding advisory product. Hiring relationship managers.',
    technologies: ['React', 'Java', 'Kafka', 'GCP'],
  },
  {
    id: 'co_19', name: 'Druva', website: 'druva.com',
    industry: 'SaaS', city: 'Pune', state: 'Maharashtra', country: 'India',
    employeeCount: 1500, revenue: '₹700 Cr', fundingStage: 'Series H',
    intentStatus: 'WARM', leadScore: 70, whyNowScore: 63,
    relationshipStatus: 'PROSPECT',
    description: 'Cloud data protection and management platform.',
    recentDevelopments: 'Expanding partner network. Looking for channel sales partners.',
    technologies: ['Go', 'React', 'AWS', 'PostgreSQL'],
  },
  {
    id: 'co_20', name: 'Nimble (NimbleEdge)', website: 'nimbleedge.ai',
    industry: 'SaaS', city: 'Bangalore', state: 'Karnataka', country: 'India',
    employeeCount: 120, revenue: '₹20 Cr', fundingStage: 'Series A',
    intentStatus: 'HOT', leadScore: 92, whyNowScore: 90,
    relationshipStatus: 'PROSPECT',
    description: 'On-device AI inference platform for enterprises.',
    recentDevelopments: 'Just raised Series A. Aggressively building enterprise sales. Hiring BDRs.',
    technologies: ['Python', 'C++', 'Rust', 'ONNX'],
  },
  {
    id: 'co_21', name: 'Airmeet', website: 'airmeet.com',
    industry: 'SaaS', city: 'Bangalore', state: 'Karnataka', country: 'India',
    employeeCount: 300, revenue: '₹80 Cr', fundingStage: 'Series B',
    intentStatus: 'WARM', leadScore: 64, whyNowScore: 55,
    relationshipStatus: 'PROSPECT',
    description: 'Virtual events and webinar platform for B2B companies.',
    recentDevelopments: 'Partnership with HubSpot announced. Looking for CRM integration partners.',
    technologies: ['React', 'Node.js', 'WebRTC', 'AWS'],
  },
  {
    id: 'co_22', name: 'Spendflo', website: 'spendflo.com',
    industry: 'SaaS', city: 'Chennai', state: 'Tamil Nadu', country: 'India',
    employeeCount: 150, revenue: '₹30 Cr', fundingStage: 'Series A',
    intentStatus: 'HOT', leadScore: 88, whyNowScore: 84,
    relationshipStatus: 'PROSPECT',
    description: 'SaaS spend management and procurement optimization platform.',
    recentDevelopments: 'Raised $11M Series A. Expanding sales team. Looking for AI sales tools.',
    technologies: ['React', 'Python', 'PostgreSQL', 'AWS'],
  },
  {
    id: 'co_23', name: 'Volopay', website: 'volopay.com',
    industry: 'FinTech', city: 'Bangalore', state: 'Karnataka', country: 'India',
    employeeCount: 250, revenue: '₹60 Cr', fundingStage: 'Series A',
    intentStatus: 'WARM', leadScore: 71, whyNowScore: 60,
    relationshipStatus: 'PROSPECT',
    description: 'Corporate spend management and cards platform.',
    recentDevelopments: 'Expanding to Singapore and Australia. Building partnership integrations.',
    technologies: ['React', 'Node.js', 'PostgreSQL'],
  },
  {
    id: 'co_24', name: 'Unacademy', website: 'unacademy.com',
    industry: 'EdTech', city: 'Bangalore', state: 'Karnataka', country: 'India',
    employeeCount: 8000, revenue: '₹2,000 Cr', fundingStage: 'Series J',
    intentStatus: 'COLD', leadScore: 38, whyNowScore: 22,
    relationshipStatus: 'PROSPECT',
    description: 'Online learning platform for competitive exam preparation.',
    recentDevelopments: 'Restructuring business. Reduced workforce significantly.',
    technologies: ['React', 'Django', 'PostgreSQL', 'AWS'],
  },
  {
    id: 'co_25', name: 'Khatabook', website: 'khatabook.com',
    industry: 'FinTech', city: 'Bangalore', state: 'Karnataka', country: 'India',
    employeeCount: 600, revenue: '₹150 Cr', fundingStage: 'Series C',
    intentStatus: 'WARM', leadScore: 62, whyNowScore: 50,
    relationshipStatus: 'PROSPECT',
    description: 'Digital ledger and business management app for SMBs.',
    recentDevelopments: 'Expanding into MSME lending. Hiring product partnerships team.',
    technologies: ['React Native', 'Node.js', 'MongoDB'],
  },
  {
    id: 'co_26', name: 'Wingify (VWO)', website: 'vwo.com',
    industry: 'SaaS', city: 'Delhi', state: 'Delhi', country: 'India',
    employeeCount: 500, revenue: '₹200 Cr', fundingStage: 'Bootstrapped',
    intentStatus: 'HOT', leadScore: 84, whyNowScore: 78,
    relationshipStatus: 'PROSPECT',
    description: 'Conversion optimization and A/B testing platform.',
    recentDevelopments: 'VWO Insights AI launch. Seeking AI integration partners.',
    technologies: ['React', 'Python', 'PostgreSQL', 'Redis'],
  },
  {
    id: 'co_27', name: 'Plum', website: 'plumhq.com',
    industry: 'InsurTech', city: 'Bangalore', state: 'Karnataka', country: 'India',
    employeeCount: 300, revenue: '₹100 Cr', fundingStage: 'Series B',
    intentStatus: 'WARM', leadScore: 69, whyNowScore: 58,
    relationshipStatus: 'PROSPECT',
    description: 'Group health insurance and employee benefits platform.',
    recentDevelopments: 'Expanding enterprise segment. Partnership with HR tech platforms.',
    technologies: ['React', 'Python', 'PostgreSQL', 'AWS'],
  },
  {
    id: 'co_28', name: 'Sprinklr', website: 'sprinklr.com',
    industry: 'SaaS', city: 'Gurgaon', state: 'Haryana', country: 'India',
    employeeCount: 4000, revenue: '₹1,800 Cr', fundingStage: 'Public (NYSE)',
    intentStatus: 'HOT', leadScore: 90, whyNowScore: 86,
    relationshipStatus: 'PROSPECT',
    description: 'Unified customer experience management platform.',
    recentDevelopments: 'Launching AI-powered SDR tool. Active procurement for outreach automation.',
    technologies: ['React', 'Java', 'Kafka', 'AWS'],
  },
  {
    id: 'co_29', name: 'Kaleyra', website: 'kaleyra.com',
    industry: 'SaaS', city: 'Bangalore', state: 'Karnataka', country: 'India',
    employeeCount: 800, revenue: '₹400 Cr', fundingStage: 'Public (NYSE)',
    intentStatus: 'WARM', leadScore: 66, whyNowScore: 54,
    relationshipStatus: 'PROSPECT',
    description: 'Cloud communications platform (SMS, voice, chat APIs).',
    recentDevelopments: 'Expanding partnership program globally. Hiring BD managers.',
    technologies: ['Java', 'React', 'PostgreSQL', 'Twilio'],
  },
  {
    id: 'co_30', name: 'Kovai.co', website: 'kovai.co',
    industry: 'SaaS', city: 'Coimbatore', state: 'Tamil Nadu', country: 'India',
    employeeCount: 200, revenue: '₹50 Cr', fundingStage: 'Bootstrapped',
    intentStatus: 'HOT', leadScore: 82, whyNowScore: 75,
    relationshipStatus: 'PROSPECT',
    description: 'Microsoft Azure integration and governance SaaS platform.',
    recentDevelopments: 'Seeking AI sales automation to scale outbound. Budget approved Q4.',
    technologies: ['React', '.NET', 'Azure', 'SQL Server'],
  },
]

export const DEMO_CONTACTS = [
  // Razorpay contacts
  { id: 'ct_1', companyId: 'co_2', name: 'Rahul Sharma', role: 'Head of Partnerships', department: 'Partnerships', seniority: 'Director', email: 'rahul.sharma@razorpay.com', emailVerified: true, location: 'Bangalore', relevanceReason: 'Decision maker for vendor partnerships. Active in fintech BD events.', confidence: 0.92 },
  { id: 'ct_2', companyId: 'co_2', name: 'Priya Menon', role: 'VP Business Development', department: 'Business Development', seniority: 'VP', email: 'priya.menon@razorpay.com', emailVerified: true, location: 'Bangalore', relevanceReason: 'Leads all external partnership evaluation and onboarding.', confidence: 0.88 },

  // BrowserStack contacts
  { id: 'ct_3', companyId: 'co_6', name: 'Arjun Kapoor', role: 'Director of Technology Partnerships', department: 'Technology', seniority: 'Director', email: 'arjun.kapoor@browserstack.com', emailVerified: true, location: 'Mumbai', relevanceReason: 'Owns the RFP evaluation for AI testing tools.', confidence: 0.95 },
  { id: 'ct_4', companyId: 'co_6', name: 'Kavita Nair', role: 'Head of Procurement', department: 'Procurement', seniority: 'Senior Manager', email: 'kavita.nair@browserstack.com', emailVerified: false, location: 'Mumbai', relevanceReason: 'Manages vendor evaluation and contract negotiation.', confidence: 0.78 },

  // Freshworks contacts
  { id: 'ct_5', companyId: 'co_3', name: 'Aditya Kumar', role: 'VP Partnerships', department: 'Partnerships', seniority: 'VP', email: 'aditya.kumar@freshworks.com', emailVerified: true, location: 'Chennai', relevanceReason: 'Driving Freddy AI partnership program.', confidence: 0.90 },

  // Darwinbox contacts
  { id: 'ct_6', companyId: 'co_9', name: 'Sneha Gupta', role: 'Head of Sales', department: 'Sales', seniority: 'Director', email: 'sneha.gupta@darwinbox.com', emailVerified: true, location: 'Hyderabad', relevanceReason: 'Driving AI hiring module vendor evaluation.', confidence: 0.87 },

  // Spendflo contacts
  { id: 'ct_7', companyId: 'co_22', name: 'Navin Rastogi', role: 'CEO', department: 'Leadership', seniority: 'C-Suite', email: 'navin@spendflo.com', emailVerified: true, location: 'Chennai', relevanceReason: 'Founder driving AI sales tooling decisions post funding.', confidence: 0.93 },
  { id: 'ct_8', companyId: 'co_22', name: 'Pooja Krishnan', role: 'VP Sales', department: 'Sales', seniority: 'VP', email: 'pooja@spendflo.com', emailVerified: true, location: 'Chennai', relevanceReason: 'Building sales team and evaluating automation tools.', confidence: 0.89 },

  // NimbleEdge contacts
  { id: 'ct_9', companyId: 'co_20', name: 'Vishal Mehta', role: 'Co-Founder & CEO', department: 'Leadership', seniority: 'C-Suite', email: 'vishal@nimbleedge.ai', emailVerified: true, location: 'Bangalore', relevanceReason: 'Leading enterprise sales strategy post Series A.', confidence: 0.96 },

  // Sprinklr contacts
  { id: 'ct_10', companyId: 'co_28', name: 'Ritu Anand', role: 'Director, Sales Operations', department: 'Sales', seniority: 'Director', email: 'ritu.anand@sprinklr.com', emailVerified: true, location: 'Gurgaon', relevanceReason: 'Evaluating outreach automation vendors.', confidence: 0.91 },

  // MoEngage
  { id: 'ct_11', companyId: 'co_17', name: 'Kapil Verma', role: 'Head of Strategic Partnerships', department: 'Partnerships', seniority: 'Senior Manager', email: 'kapil@moengage.com', emailVerified: true, location: 'Bangalore', relevanceReason: 'Looking for AI sales integration partners.', confidence: 0.85 },

  // Clevertap
  { id: 'ct_12', companyId: 'co_12', name: 'Tanvi Shah', role: 'VP of Sales', department: 'Sales', seniority: 'VP', email: 'tanvi.shah@clevertap.com', emailVerified: true, location: 'Mumbai', relevanceReason: 'Owns RFP evaluation for AI-powered SDR tools.', confidence: 0.93 },
]

export const DEMO_DEALS = [
  { id: 'deal_1', companyId: 'co_6', contactId: 'ct_3', name: 'BrowserStack AI Testing Integration', value: 2400000, probability: 75, stage: 'MEETING_COMPLETED', health: 'HEALTHY', nextBestAction: 'Send proposal by Friday — they requested it after meeting.', currency: 'INR' },
  { id: 'deal_2', companyId: 'co_3', contactId: 'ct_5', name: 'Freshworks Freddy AI Partnership', value: 5000000, probability: 60, stage: 'ENGAGED', health: 'NEEDS_ATTENTION', healthReason: 'No activity for 8 days', nextBestAction: 'Follow up with partnership deck — 8 days since last contact.', currency: 'INR' },
  { id: 'deal_3', companyId: 'co_2', contactId: 'ct_1', name: 'Razorpay Capital Sales Automation', value: 3600000, probability: 45, stage: 'CONTACTED', health: 'HEALTHY', nextBestAction: 'Book discovery call — positive initial response received.', currency: 'INR' },
  { id: 'deal_4', companyId: 'co_22', contactId: 'ct_7', name: 'Spendflo Outreach Suite', value: 1200000, probability: 85, stage: 'PROPOSAL', health: 'HEALTHY', nextBestAction: 'Follow up on proposal sent 3 days ago — high intent signals.', currency: 'INR' },
  { id: 'deal_5', companyId: 'co_9', contactId: 'ct_6', name: 'Darwinbox AI Hiring Module', value: 1800000, probability: 55, stage: 'QUALIFIED', health: 'NEEDS_ATTENTION', healthReason: 'Decision delayed — budget review in progress', nextBestAction: 'Send ROI case study from similar HR tech company.', currency: 'INR' },
  { id: 'deal_6', companyId: 'co_28', contactId: 'ct_10', name: 'Sprinklr SDR Automation', value: 4200000, probability: 70, stage: 'NEGOTIATION', health: 'AT_RISK', healthReason: 'Competitor shortlisted — price negotiation ongoing', nextBestAction: 'Offer extended trial + executive sponsor call urgently.', currency: 'INR' },
]

export const DEMO_MEETINGS = [
  {
    id: 'mtg_1', companyId: 'co_6', contactId: 'ct_3', dealId: 'deal_1',
    title: 'BrowserStack — Product Demo & Discovery',
    scheduledAt: new Date(Date.now() + 2 * 60 * 60 * 1000), // 2 hours from now
    duration: 60, meetLink: 'https://meet.google.com/abc-defg-hij',
    agenda: 'AI testing tool evaluation. Budget discussion. Integration requirements.',
    status: 'SCHEDULED',
  },
  {
    id: 'mtg_2', companyId: 'co_22', contactId: 'ct_7', dealId: 'deal_4',
    title: 'Spendflo — Proposal Walkthrough',
    scheduledAt: new Date(Date.now() + 24 * 60 * 60 * 1000), // tomorrow
    duration: 45, meetLink: 'https://meet.google.com/xyz-abcd-efg',
    agenda: 'Walk through commercial proposal. Address procurement concerns.',
    status: 'SCHEDULED',
  },
]

export const DEMO_ACTIVITIES = [
  { id: 'act_1', companyId: 'co_6', contactId: 'ct_3', activityType: 'LEAD_DISCOVERED', description: 'Lead discovered via ICP match — SaaS, Bangalore, 1000+ employees', source: 'AI', createdAt: new Date(Date.now() - 7 * 86400000) },
  { id: 'act_2', companyId: 'co_6', activityType: 'INTENT_DETECTED', description: 'HOT intent detected: Active RFP for AI testing tools published on LinkedIn', source: 'AI', createdAt: new Date(Date.now() - 6 * 86400000) },
  { id: 'act_3', companyId: 'co_6', contactId: 'ct_3', activityType: 'POC_IDENTIFIED', description: 'POC identified: Arjun Kapoor, Director of Technology Partnerships', source: 'AI', createdAt: new Date(Date.now() - 5 * 86400000) },
  { id: 'act_4', companyId: 'co_6', contactId: 'ct_3', activityType: 'OUTREACH_DRAFTED', description: 'AI drafted personalized email outreach — quality score 94/100', source: 'AI', createdAt: new Date(Date.now() - 4 * 86400000) },
  { id: 'act_5', companyId: 'co_6', contactId: 'ct_3', activityType: 'OUTREACH_SENT', description: 'Email sent to arjun.kapoor@browserstack.com — Subject: AI-powered testing for BrowserStack', source: 'USER', createdAt: new Date(Date.now() - 3 * 86400000) },
  { id: 'act_6', companyId: 'co_6', contactId: 'ct_3', activityType: 'REPLY_RECEIVED', description: 'Positive reply received — "Interested, let\'s schedule a call"', source: 'SYSTEM', createdAt: new Date(Date.now() - 2 * 86400000) },
  { id: 'act_7', companyId: 'co_6', contactId: 'ct_3', activityType: 'MEETING_BOOKED', description: 'Meeting scheduled: Product Demo & Discovery — 60 min via Google Meet', source: 'AI', createdAt: new Date(Date.now() - 86400000) },
]

export const DEMO_INTENT_SIGNALS = [
  { id: 'sig_1', companyId: 'co_6', signalType: 'RFP', description: 'Published RFP for AI-powered testing and QA automation tools', source: 'LinkedIn', confidence: 0.95, detectedDate: new Date(Date.now() - 6 * 86400000) },
  { id: 'sig_2', companyId: 'co_2', signalType: 'HIRING', description: 'Hiring 5 BD managers across India — signals enterprise expansion', source: 'LinkedIn Jobs', confidence: 0.88, detectedDate: new Date(Date.now() - 3 * 86400000) },
  { id: 'sig_3', companyId: 'co_3', signalType: 'PARTNERSHIP', description: 'Freddy AI partner program announced — seeking integration partners', source: 'Press Release', confidence: 0.92, detectedDate: new Date(Date.now() - 4 * 86400000) },
  { id: 'sig_4', companyId: 'co_9', signalType: 'PRODUCT_LAUNCH', description: 'AI hiring module launching Q1 — requires vendor ecosystem', source: 'Company Blog', confidence: 0.85, detectedDate: new Date(Date.now() - 5 * 86400000) },
  { id: 'sig_5', companyId: 'co_22', signalType: 'FUNDING', description: 'Raised $11M Series A — expanding sales team aggressively', source: 'TechCrunch', confidence: 0.97, detectedDate: new Date(Date.now() - 8 * 86400000) },
  { id: 'sig_6', companyId: 'co_28', signalType: 'TECHNOLOGY', description: 'Evaluating AI-powered SDR tools — internal Slack community post surfaced', source: 'Social Listening', confidence: 0.82, detectedDate: new Date(Date.now() - 2 * 86400000) },
]

export const DEMO_STATS = {
  leadsGenerated: 156,
  qualifiedLeads: 42,
  qualificationRate: 26.9,
  outreachSent: 89,
  responseRate: 34.8,
  positiveResponseRate: 18.2,
  meetings: 12,
  meetingConversion: 28.6,
  proposals: 6,
  winRate: 33.3,
  pipelineValue: 18200000,
  avgSalesCycle: 28,
}
